config/routes.rb
Rails.application.routes.draw do
  root 'recent#index'
  get 'recent' => 'recent#index'

  resources :messages, only: [:index, :new, :show, :create, :destroy]

end

app/models/message.rb
class Message < ActiveRecord::Base
  %i(to from message).each{|f|
    validates f, presence: true
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        dest = params[:redirect_to]
        dest = dest.blank? ? messages_path : dest
        format.html { redirect_to dest, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:from, :to, :message, :stamp)
    end
end

app/controllers/recent_controller.rb
class RecentController < ApplicationController
  def index
    @messages = Message.order("created_at DESC").page(params[:page]).per 10
    @message = Message.new
    @redirect_to = recent_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/recent_helper.rb
module RecentHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "arigatobook" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <a class="navbar-brand" href="/">arigatobook</a>
      <ul class="nav navbar-nav">
	<li><a href="/#say">Say</a></li>
	<li><a href="/#runtime_information">RuntimeInfo</a></li>
      </ul>
    </nav>

    <div class="jumbotron">
      <div class="container">
	<p>
	<%= image_tag 'arigatobook.png' %>
	</p>
	<p>
	  Say "ありがとう（arigato）" "Thank you" "Gracias" "Merci" "Danke" "धन्यवाद।" "谢谢" "شكرا" "Спасибо" in your words to someone great!
	</p>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Koichi Sasada 2015</p>
      </footer>

    </div> <!-- /container -->
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message, :html => { :class => "form-horizontal message" } do |f| %>

    <% if @message.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :from, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :from, :class => 'form-control' %>
    </div>
    <%= error_span(@message[:from]) %>
  </div>
  <div class="control-group">
    <%= f.label :to, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :to, :class => 'form-control' %>
    </div>
    <%= error_span(@message[:to]) %>
  </div>
  <div class="control-group">
    <%= f.label :stamp, :class => 'control-label' %>
    <div class="controls">
      <% files = Dir.glob('app/assets/images/stamp/*.{png,gif}').sort.map do |path| %>
	  <% filename = File.basename(path) %>
      <% end %>
      <%= f.select :stamp, files.map.with_index{|e, i| [e, e,
        {class: 'ImageOption', style: "background-image: url(#{image_path 'stamp/' +  e}"}]} %>
    </div>
    <%= error_span(@message[:message]) %>
  </div>
  <div class="control-group">
    <%= f.label :message, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :message, :class => 'form-control' %>
    </div>
    <%= error_span(@message[:message]) %>
  </div>

  <%= hidden_field_tag :redirect_to, @redirect_to %>

  <%= f.submit nil, :class => 'btn btn-primary' %>
<% end %>

app/views/messages/edit.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/messages/index.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:from) %></th>
      <th><%= model_class.human_attribute_name(:to) %></th>
      <th><%= model_class.human_attribute_name(:message) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= link_to message.id, message_path(message) %></td>
        <td><%= message.from %></td>
        <td><%= message.to %></td>
        <td><%= message.message %></td>
        <td><%=l message.created_at %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      message_path(message),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_message_path,
            :class => 'btn btn-primary' %>

app/views/messages/new.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/messages/show.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:from) %>:</strong></dt>
  <dd><%= @message.from %></dd>
  <dt><strong><%= model_class.human_attribute_name(:to) %>:</strong></dt>
  <dd><%= @message.to %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stamp) %>:</strong></dt>
  <dd><%= image_tag(@message.stamp.blank? ? 'stamp/hanamaru02-002.gif' : "stamp/#{@message.stamp}") %></dd>
  <dt><strong><%= model_class.human_attribute_name(:message) %>:</strong></dt>
  <dd><%= @message.message %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              messages_path, :class => 'btn btn-default'  %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              message_path(@message),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/recent/index.html.erb
<h2 id='say'>Say your arigato (thank you) to someone great!</h2>

<%= render template: 'messages/_form' %>

<h2 id='recent'>Recent Messages</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Message</th>
      <th>Time</th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |m| %>
    <tr>
      <td><%= m.from %></td>
      <td><%= m.to %></td>
      <td><div><%= image_tag m.stamp.blank? ? 'stamp/hanamaru02-002.gif' : "stamp/#{m.stamp}" %> <%= m.message %></td>
      <td><%= link_to m.created_at, m %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @messages %>

<h2 id='runtime_information'>Runtime information</h2>

<ul>
  <% %w(
    /gc_tracer
    /gc_tracer/text
    /allocation_tracer/
    /allocation_tracer/allocated_count_table
    /allocation_tracer/freed_count_table
    /allocation_tracer/lifetime_table
    ).each do |page| %>
  <li><a href='<%= page %>'><%= page %></a></li>
  <% end %>
</ul>